{
 "title": "Driving",
 "tags": [ "tesla" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vehicle_name",
    "query": "select distinct(display_name) from (select * from charge_state)"
   }
  ]
 },
 "panels": [
  {
   "title": "Odometer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "vehicle_state",
     "query": "SELECT last(\"odometer\") * 1.60934 FROM \"vehicle_state\" WHERE (\"metric\" = 'odometer') ",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "odometer" }
     ]
    }
   ]
  },
  {
   "title": "Drivemode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT last(\"shift_state\") FROM \"drive_state\" WHERE (\"metric\" = 'shift_state' AND \"display_name\" =~ /^$vehicle_name$/) ",
     "select": [
      [
       { "params": [ "shift_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "shift_state" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "est_battery_range" ], "type": "field" },
       { "params": [ "*1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "est_battery_range" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Outside Temperatur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "outside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "outside_temp" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Inside Temperatur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "inside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "inside_temp" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "SELECT \"native_latitude\" AS \"latitude\", \"native_longitude\" AS \"longitude\" FROM \"drive_state\" WHERE (\"display_name\" = 'Ulysses') AND time >= now() - 6h",
     "select": [
      [
       { "params": [ "native_latitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "native_latitude" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "select": [
      [
       { "params": [ "native_longitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "native_longitude" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "format": "velocitykmh",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT last(\"speed\") * 1.60934 FROM \"drive_state\" WHERE (\"metric\" = 'speed' AND \"display_name\" =~ /^$vehicle_name$/)",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "speed" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "alias": "speed",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "SELECT mean(\"speed\") * 1.60934 FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/ AND \"metric\" = 'speed') AND $timeFilter GROUP BY time(5s) fill(previous)",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "speed" }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "kwatt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT last(\"power\") FROM \"drive_state\" WHERE (\"metric\" = 'power' AND \"display_name\" =~ /^$vehicle_name$/)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Revenue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "power",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "SELECT mean(\"power\") FROM \"drive_state\" WHERE (\"metric\" = 'power' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Sleepstate",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "vehicle_state",
     "query": "SELECT \"state\" FROM \"vehicle_state\" WHERE (\"metric\" = 'state' AND \"display_name\" =~ /^$vehicle_name$/) AND  $timeFilter\n",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "state" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive Mode",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT \"shift_state\" FROM \"drive_state\" WHERE (\"metric\" = 'shift_state' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "shift_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "shift_state" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  }
 ]
}